### ISSUE TITLE
Activated but message on desktop persists

### ISSUE THREAD

**Issue by murilotdb** [sysconf16/ltsc-2021-activator#1]
Hi!
Your activator script seems to work but, after running it, I still see the message at the bottom right corner on the desktop: "Test mode"
Is this normal? I thought the message would disappear after running the script.

Thank you!

![image](https://user-images.githubusercontent.com/79963977/226398021-13367e08-6d22-4792-aa1a-6358873d0c23.png)

**Comment by sysconf16** [comment]
Test mode is a feature of Windows separate to activation.

Please see here: https://www.dell.com/support/kbdoc/en-uk/000190354/removing-the-test-mode-watermark-from-the-windows-10-desktop
